backend:
  name: git-gateway
local_backend: true
media_folder: public/cms-images
public_folder: /cms-images
publish_mode: editorial_workflow
display_url: http://localhost:3000

collections:
  - label: Homepage
    name: homepage
    files:
      - label: Algemeen
        name: homepage_general
        file: cms/collections/home_general.md
        fields:
          - {
              label: Titel,
              name: title,
              widget: string,
              default: Dit is de titel,
            }
      - label: Artikels
        name: homepage_articles
        file: cms/collections/home_articles.md
        fields:
          - label: Artikels
            name: articles
            widget: list
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Content, name: body, widget: markdown }
              - label: Afbeeldingen
                name: images
                widget: list
                fields:
                  - { label: Afbeelding, name: image, widget: image }
                  - { label: Onderwerp, name: description, widget: markdown }

  - label: Pagina's
    label_singular: Pagina
    name: pages
    folder: cms/collections/pages
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - label: Artikels
        name: articles
        widget: list
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Content, name: body, widget: markdown }
          - label: Afbeeldingen
            name: images
            widget: list
            fields:
              - { label: Afbeelding, name: image, widget: image }
              - { label: Onderwerp, name: description, widget: markdown }
