backend:
  name: git-gateway
local_backend: true
media_folder: public/cms-images
public_folder: /cms-images
publish_mode: editorial_workflow
display_url: http://localhost:3000

collections:
  - label: Homepage
    name: homepage
    files:
      - label: Structuur
        name: homepage_structure
        file: "cms/collections/home.md"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - {
              label: Knop,
              name: button,
              widget: string,
              hint: Hier kan je de tekst van de knop aanpassen,
            }
          - label: Artikels
            name: articles
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - label: Afbeeldingen
                name: images
                widget: list
                fields:
                  - { label: "Afbeelding", name: "image", widget: "image" }
                  - {
                      label: "Onderwerp",
                      name: "description",
                      widget: "markdown",
                    }

  - label: "Pagina's"
    label_singular: "Pagina"
    name: "pages"
    folder: "cms/collections/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: Artikels
        name: articles
        widget: list
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: Afbeeldingen
            name: images
            widget: list
            fields:
              - { label: "Afbeelding", name: "image", widget: "image" }
              - { label: "Onderwerp", name: "description", widget: "markdown" }

    #  - label: "Lees Artikels"
    #    label_singular: "Lees Artikel"
    #    name: "lees_artikels"
    #    folder: "cms/collections/articles"
    #    identifier_field: name
    #    create: true
    #    filter: { field: "type", value: "Lees" }
    #    fields:
    #      - { label: "Type", name: "type", widget: "hidden" }
    #      - { label: "Title", name: "title", widget: "string" }
    #      - { label: "Publish Date", name: "date", widget: "datetime" }
    #      - { label: "Body", name: "body", widget: "markdown" }

    #  - label: "Kijk Artikels"
    #    label_singular: "Kijk Artikel"
    #    name: "kijk_artikels"
    #    folder: "cms/collections/articles"
    #    identifier_field: name
    #    create: true
    #    filter: { field: "type", value: "Kijk" }
    #    fields:
    #      - { label: "Type", name: "type", widget: "hidden" }
    #      - { label: "Title", name: "title", widget: "string" }
    #      - { label: "Publish Date", name: "date", widget: "datetime" }
    #      - label: "Images"
    #        allow_multiple: true
    #        name: "images"
    #        widget: "image"
    #        choose_url: true
    #        media_library:
    #          config:
    #            multiple: true
    #      - { label: "Body", name: "body", widget: "markdown" }

    # - name: "home"
    #   identifier_field: title
    #   label: "Home"
    #   label_singular: "Home"
    #   folder: "cms/collections/home"
    #   create: true
    #   fields:
    #     - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
    #     - { label: "Title", name: "title", widget: "string" }
    #     - { label: "Publish Date", name: "date", widget: "datetime" }
    #     - {
    #         label: "Featured Image",
    #         name: "thumbnail",
    #         widget: "image",
    #         required: false,
    #       }
    #     - { label: "Body", name: "body", widget: "markdown" }
